import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <Navbar />
      <body className={inter.className}>{children}</body>
    </html>
  );
}

//Ignore this comment im just making sure my pushing works
